### ISSUE TITLE
PostAsync does not respond

### ISSUE THREAD

**Issue by redunuri** [dgwaldo/ags-resource-proxy#1]
HttpClient(clientName).PostAsync(tokenUri, new FormUrlEncodedContent(formData))
Newer get response back

**Comment by dgwaldo** [comment]
Can you share your setup code?

**Comment by redunuri** [comment]
I am using user based login. I dint change any code except proxy.config.json values.
For user based login url and oauth2Endpoint same right?


Regards,

Ravinder Edunuri,

480-255-4445

________________________________

**Comment by dgwaldo** [comment]
User based login would not go through the code that requests tokens. User based login would pass your credentials to the http client that gets created in Startup.cs

**Comment by redunuri** [comment]
okay I will try that. Thank you so much the help!


Regards,

Ravinder Edunuri,

480-255-4445

________________________________

**Comment by redunuri** [comment]
Hi,

Not sure how to set up http client in startup.cs. I tried in different ways but not successful. Can you please help set up?
I am new to .net core also so lack of knowledge.

Thank you so much in advance.


Regards,

Ravinder Edunuri,

480-255-4445

________________________________

**Comment by dgwaldo** [comment]
Can you post your startup.cs file here?

**Comment by redunuri** [comment]
I am sorry was occupied with prod issues. Apologies delay in response. I just googled it and randomly verified.
 Lost those changes.


Regards,

Ravinder Edunuri,

480-255-4445

________________________________
