### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by pineapplegum** [dgwaldo/ags-resource-proxy#2]
Hi, thanks for your work on this project! 

I would like to use the proxy in an asp.net core web api project. In this project we use jwt-based authentication and authorization and I'm wondering if it is possible to only allow the proxy to be used by authorized users (i.e. users who have a valid jwt token)?

**Comment by dgwaldo** [comment]
I'm assuming your doing some OAuth2 wire up?  Your users will be authenticated and that authentication should be reflected in your user on the context. 

If you look at the code below you'll see in the UseWhen function we check that context.User.Identity.IsAuthenticated. If I understand your question correctly I think that's what your after.

```
app.UseWhen(context => {
				return context.Request.Path.Value.ToLower().StartsWith(@"/proxy/proxy.ashx", StringComparison.OrdinalIgnoreCase)
				&& context.User.Identity.IsAuthenticated;
			},
				builder =>
					builder.UseAgsProxyServer(
					app.ApplicationServices.GetService<IProxyConfigService>(),
					app.ApplicationServices.GetService<IProxyService>(),
					app.ApplicationServices.GetService<IMemoryCache>())
				);
```

**Comment by pineapplegum** [comment]
Thanks for the quick reply! 

Yes, users authenticate and receive a JWT token which is later used to authorize calls to the web api. In order for context.User.Identity.IsAuthenticated to be true, I need to set the request header Authorization to "Bearer jwtTokenIsInsertedHere" whenever I send a call to the proxy. When doing this, context.User.Identity.IsAuthenticated equals true, however, the response from the proxy is: 

`error: {code: 498, message: "Invalid Token", details: []}`

My proxy.config.json looks like this: 

`{  
  "allowedReferrers": ["*"],  
  "useAppPoolIdentity": false,
  "tokenCacheMinutes": 29,  
  "serverUrls": [    
    {
      "url": "http://my-domain-url/arcgis/rest/services/featureservice/Servicename/FeatureServer/0",      
      "username": "*****",
      "password": "*****"
    }
  ]
}`

By the way, if I do not add the "&& context.User.Identity.IsAuthenticated", the proxy works perfect, but then the proxy is open for everyone which is what I'm trying to prevent.

**Comment by pineapplegum** [comment]
Ok, after more investigation I've found that the error I receive ("Invalid token") is caused by the fact that the jwt token I pass in the authorization header (to ensure that context.User.Identity.IsAuthenticated is true) when calling the proxy is forwarded to the mapservice. The behaviour is the same in the regular resource-proxy from esri. 

In other words, I don't think this is a problem with the AGS proxy but rather with my setup for authentication and authorization.

**Comment by dgwaldo** [comment]
Try taking a look at documentation from Auth0 or https://www.identityserver.com/documentation/ documentation. Might help you with what your trying to accomplish.  You only get one Authorization header... 

This is something that I feel is very unclear in lots of integration scenarios. What to do if you need to Auth two different API's but you have one Authorization header? Your API needs it set, but it's going to get passed on through the proxy to ArcGIS Server... I think the typical use case for this proxy would with Cookies on a MVC type endpoint, thus the issue wouldn't occur. 

You might try branching my code and basically clearing the Authorization header in the proxy before requests start. If that works we can go from there...

**Comment by pineapplegum** [comment]
Thanks for the advice. I ended up making a simple middleware that removes the authorization header before the request is forwarded to the proxy, ie: 

1. Request is sent from client with authorization header set to jwt token
2. When request is received in the backend and authorized, we use a middleware to remove the authorization header before the request is processed by the proxy. 
3. The request is processed by the proxy and returns the result. 

Not sure if this is the optimal way of doing things, but it works in my scenario. 

Anyway, thanks for the help. I will close the issue now.
