### ISSUE TITLE
Implementation compared to original .Net resource proxy

### ISSUE THREAD

**Issue by nbw71791** [dgwaldo/ags-resource-proxy#3]
I'm a little confused as to how this should be implemented when compared to the ESRI provided resource proxy. In their documentation and guidance blog post, the DotNet folder containing the .ashx and .config files are hosted on IIS.

Is this still necessary for the .Net Core version, or is the proxy hosted a different way that I am not familiar with?

I noticed in this project's ReadMe you mention that you can direct the middleware routing to the proxy's location, so I am assuming you have to deploy it to that location, but I wasn't sure if that had to be done via IIS like the original resource proxy, or a different way. Especially since .Net Core uses IIS Express for local debugging.

**Comment by dgwaldo** [comment]
You can place the config file where ever you like, as long as you can configure your application to hit the path. If you want to place it in a folder called DotNet that is fine. Although I'd recommend naming it something else. 

In the startup.cs file the following line is the one that tells the middleware where to find the config.

This example would have the config at the root of your project. Not in a any folder.
	`services.AddSingleton<IProxyConfigService, ProxyConfigService>((a) => new ProxyConfigService(a.GetService<IHostingEnvironment>(), "proxy.config.json"));`

This example would have the config placed in a folder called Proxy.
`services.AddSingleton<IProxyConfigService, ProxyConfigService>((a) => new ProxyConfigService(a.GetService<IHostingEnvironment>(), "/Proxy/proxy.config.json"));`

As far as what you want the proxy address to be... Most folks likely have client side code that's already looking for proxy.ashx... Obviously we aren't using ashx anymore. However, the middleware doesn't care. 

Take a look at the following. Note the .StartsWith() function. If you made that say, starts with "bob" then you'd call "bob" to proxy things. As you can see I kept the proxy.ashx path here so any references to it in client code did not need to be modified when moving to .net core.
```
app.UseWhen(context => {
				return context.Request.Path.Value.ToLower().StartsWith(@"/proxy/proxy.ashx", StringComparison.OrdinalIgnoreCase)
				&& context.User.Identity.IsAuthenticated;
			},
				builder =>
					builder.UseAgsProxyServer(
					app.ApplicationServices.GetService<IProxyConfigService>(),
					app.ApplicationServices.GetService<IProxyService>(),
					app.ApplicationServices.GetService<IMemoryCache>())
				);
```

Hope that helps.  If you feel the documentation can be improved let me know how you'd do that...

**Comment by nbw71791** [comment]
The config placement makes sense to me. And I think the documentation overall is good. It is starting to make more sense to me, thanks for the explanation. 

I think the key thing that I was missing was the fact that the middleware you've written now holds the code that used to be hosted in proxy.ashx. There is no longer a need to self host proxy.ashx via IIS.

The .StartsWith() function is used to "intercept" requests and run them through the middleware, so long as the requests fulfill the condition of StartsWith().

**Comment by dgwaldo** [comment]
Yes well stated.

**Comment by nbw71791** [comment]
Thanks for your help, and for stepping up to create the middleware for .Net Core users.

**Comment by dgwaldo** [comment]
Your welcome, sure wish ESRI would step it up ;)

**Comment by amjadaliamjad** [comment]
I done all same as in documentation and add server url and credential in json config file and put config file at root level and call from arcgis javascript api as as '/proxy/proxy.ashx' but arcgis javascript api promt for  login . it seem like this proxy not work or not pick credentials from file. i am  using asp.net core 3.1 mvc. when i hit direct in browser then get this message 
{"error":{"code":499,"message":"Token Required","details":[]}} when
