### ISSUE TITLE
Use in asp.net core 2.1

### ISSUE THREAD

**Issue by pineapplegum** [dgwaldo/ags-resource-proxy#4]
Hi, 

Thanks for this great implementation. 

I would like to use the proxy in an asp.net core 2.1 project, but it seems as if I need the 2.2 version in order to get it to work when I test it. 

Do you have any idea on how I could go about using the proxy in a project that uses asp.net core 2.1?

**Comment by dgwaldo** [comment]
The compile targets could be updated to compile for both versions. I'm not
sure when I can get to it, but if you look up compile targets for .net core
you'll see what I'm talking about. Feel free to PR that :).

The quick and dirty is to just pull it local and compile against 2.1.
