### ISSUE TITLE
ags tokens

### ISSUE THREAD

**Issue by ghost** [dgwaldo/ags-resource-proxy#5]
Hi

Great work! 

Do you have any plans to implement the basic ArcGIS Server token login in the proxy code?

**Comment by dgwaldo** [comment]
Thankfully I'm not really working with much ESRI tech anymore :) Don't  have access to ArcGIS Server for testing, so not likely to do much myself on this code base. I'm assuming your talking about this http://enterprise.arcgis.com/en/server/latest/administer/windows/accessing-arcgis-token-secured-web-services.htm

**Comment by ghost** [comment]
Your assumption is correct. I will consider my options - one outcome could be to implement it myself.
