### ISSUE TITLE
1.0.20 Won't Publish to Nuget

### ISSUE THREAD

**Issue by mattheworres** [dgwaldo/ags-resource-proxy#9]
Looks like the latest round of changes never made it to Nuget, and the error suggests that maybe AppVeyor needs a refreshed token? I'm unfamiliar with using either but figured I'd raise the flag here and see if you could get this figured out quickly.  Thanks!

**Comment by mattheworres** [comment]
`Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.` per https://ci.appveyor.com/project/dgwaldo/ags-resource-proxy

**Comment by dgwaldo** [comment]
yah I saw that and went to fix it, updated the token and kept getting that error, haven't had time to get back to it yet sorry.

**Comment by dgwaldo** [comment]
Reached out to Nuget support, will keep on this as I have time.

**Comment by mattheworres** [comment]
I appreciate it, I completely understand how tough it is to track down these sorts of things on open source libraries, especially ones you don't even use anymore. Much appreciated!
